name: ci

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDk
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run unit tests
        run: echo "Hello, World!"

   

          
